version: '3'

services:
  xmrig:
    image: bananajamma/xmrig
    deploy:
      mode: global
      restart_policy:
        condition: any
    devices: [
      "/dev/hugepages:/dev/hugepages"
    ]
    command: [
      "--donate-level=0",
      "--tls",
      "-o","pool.supportxmr.com:9000",
      "-u","42qmSdJMXvzSzkfhwwwEYYDdsqL1RngQnfQV2RW3cGsLMZ43Y6LV62UhNUY2fHqq58Xr5ZDxE8MFo3AHEqsvkZNzUbnLGTk",
      "-p","server0",
      "-k",
      "--max-cpu-usage=98"
    ]
