version: '3'

services:
  miner:
    image: kannix/monero-miner
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes: [
      "/dev/hugepages:/dev/hugepages"
    ]
    command:
      - "--url=pool.supportxmr.com:3333"
      - "--user=42qmSdJMXvzSzkfhwwwEYYDdsqL1RngQnfQV2RW3cGsLMZ43Y6LV62UhNUY2fHqq58Xr5ZDxE8MFo3AHEqsvkZNzUbnLGTk"
      - "--pass=x"
      - "-k"
      - "--coin=monero"
      - "--donate-level=1"
